### ISSUE TITLE
Firehose

### ISSUE THREAD

**Issue by TomDonoghue** [voytekresearch/Resources#1]
What's the status of the firehose?

I've lost track of the dropbox vs. google drive, and what's up to date. Most recently we had some kind of voting system, but I'm not sure we really finished that process?
-https://docs.google.com/spreadsheets/d/1mshNuMoVS8neHYXi0FiMKyhDC7LCW5sTmoaLQk5ilZ8/edit#gid=0
-https://docs.google.com/spreadsheets/d/1_cGaE0ldt2H3gaJ0iYBs7ODocg2yaTYcVMGKz8r3fjM/edit#gid=0

Perhaps most relevantly:
- Do we have a subset of papers that are more relevant to undergrads?
- Do we have a general suggested reading list for new/visiting/rotation members?

**Comment by voytek** [comment]
I've been using dropbox to host the [firehose](https://www.dropbox.com/sh/bsliv9bkyczlffr/AAAByTfphIdD1SktG6_fN8oWa?dl=0) as well as [undergrad RA specific papers](https://www.dropbox.com/sh/93hsgldkhcl9j5h/AABb7TPj9vbwLZPtVXam2Tana?dl=0). The latter could also serve as an appropriate repository for visitors and rotation students.

Perhaps we should move all this to GitHub? That way lab members could make addition/deletion requests that allow for voting, etc.

**Comment by TomDonoghue** [comment]
I'm not super sure about using Github to host data files (pdfs) - it's not really ideal for you that: you can't for example, download a single article, and it's not even obvious, to a new user, how to download things at all. We could probably use issues, for a voting structure, regardless of where they are actually hosted? (Unless you meant use PRs?)

If those are the up to date collections / links, I think we can just add the links in the onboarding file? Is there anything up to date or relevant in the annotated bibliography / voter files I linked to, or should we scrap those?

**Comment by voytek** [comment]
Don't worry about the vote file, I guess. But yes link to the above for now. We can discuss the rest at lab meeting.

**Comment by TomDonoghue** [comment]
I think this is wildly out of date, so I'm going to close this :)
